trigger: none
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
 
- task: AzureCLI@2
  inputs:
    azureSubscription: 'd-aks-default'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -n d-aks -g ad-test
 
      # get kubelogin
      wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
      unzip kubelogin-linux-amd64.zip
      sudo mv bin/linux_amd64/kubelogin /usr/bin
      kubelogin convert-kubeconfig -l azurecli
 
      kubectl get nodes